print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "D:/Users/Jamie/Desktop/Mystery-box/Mystery-Box/Mystery Box/Assets/Gracyn/Models/Rug.mb"`)
{		
	file -o "D:/Users/Jamie/Desktop/Mystery-box/Mystery-Box/Mystery Box/Assets/Gracyn/Models/Rug.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "D:/Users/Jamie/Desktop/Mystery-box/Mystery-Box/Mystery Box/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "D:/Users/Jamie/Desktop/Mystery-box/Mystery-Box/Mystery Box/Temp/CommandPipe";

$donepipeKill = `fopen "D:/Users/Jamie/Desktop/Mystery-box/Mystery-Box/Mystery Box/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
